name: Selenium Automation
'on':
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt'
    - name: Create Reports Directory
      run: python -c "import os; os.makedirs('reports', exist_ok=True)"
    - name: Run Selenium tests with Firefox
      env:
        BASE_URL: http://stage.bytebeam.io
        FILES: Tests/test_meta.py
        SANITY: regression
      run: "if [ \"$SANITY\" == \"regression\" ]; then\n  pytest $FILES --html=reports/report.html\n\
        else\n  pytest --html=reports/report.html\nfi\n"
    - name: Upload Reports as Artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: reports
