name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  your-job-name:
    runs-on: ubuntu-latest

    steps:
      - name: Automation run
        run: python app.py

      # Your other steps here
