client: client1
content:
  name: Your Workflow Name
  true:
    push:
      branches:
      - main
  jobs:
    your-job-name:
      runs-on: ubuntu-latest
      steps:
      - name: Automation run
        run: python new.py
files: ''
mode: regression
sha: a50f76386fbaed637045345d9c97d8c422cc6f5f
